### ISSUE TITLE
Add Lib to PyPI?

### ISSUE THREAD

**Issue by PowerBroker2** [klaundal/ppigrf#2]
This seems like a really cool and useful library - would be amazing if it was "pip-installable". Any plans to add this to PyPI?

[https://realpython.com/pypi-publish-python-package/](https://realpython.com/pypi-publish-python-package/)

**Comment by klaundal** [comment]
Thanks for the comment and for the bugfix! I'll look into adding it to PyPI!

**Comment by klaundal** [comment]
This should now be possible
