### ISSUE TITLE
Feature Request: Non-Grid Multiple Value Query

### ISSUE THREAD

**Issue by PowerBroker2** [klaundal/ppigrf#3]
Would it be possible to add a parameter to `ppigrf.igrf()` that would allow me to query for IGRF values at multiple locations/dates that do not correspond to a grid?

Right now if I pass an array of lat/lon/alt/dates to the function, I have to take the diagonal of the outputs, meaning I'm wasting tons of memory and CPU cycles on IGRF calcs I don't care about.

**Comment by klaundal** [comment]
This is not completely accurate. For spatial coordinates, the code already should have the behavior that you want. The output has the same shape as the combined shape of the spatial coordinate input, using numpy broadcasting rules. For temporal / date coordinates, you are correct though (see example in the readme). The main reason it's not implemented, apart from the fact that it is not completely straightforward, is that I haven't seen a use case for it. The magnetic field changes so slowly that it doesn't make much sense to pass arrays of datetimes with high time resolution. If you need accuracy better than 1-year resolution, you would probably be better off using a more precise magnetic field model also (see for example https://github.com/ancklo/ChaosMagPy). Please let me know if you disagree, I would be curious to know if there are cases when high time resolution is useful.

**Comment by PowerBroker2** [comment]
Ok, that makes sense. Thank you!
