### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by thetazero** [klaundal/ppigrf#5]
Not sure if you are still maintaining it, but running it on `Python 3.8.8` with numpy version `1.19.2` results in:
```python
ppigrf.igrf(34.567, 45.678, 100, datetime(2021,1,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thetazero/anaconda3/lib/python3.8/site-packages/ppigrf/ppigrf.py", line 579, in igrf
    shape = np.broadcast_shapes(lon.shape, lat.shape, h.shape)
  File "/home/thetazero/.local/lib/python3.8/site-packages/numpy/__init__.py", line 214, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'broadcast_shapes'
```

**Comment by klaundal** [comment]
Ah, thanks for letting me know. Apparently `broadcast_shapes` is new in numpy 1.20, so it should work if you upgrade your version. I guess  I should update the requirements. If you try to update, please let me know if it helps or not.

**Comment by thetazero** [comment]
Works now that i've updated numpy, thanks
